kongor = {
    "agi": [
        ( "Emerald Warden", "heroes/kongor/emerald_warden" ),
        ( "Moon Queen", "heroes/kongor/krixi" ),
        ( "Andromeda", "heroes/kongor/andromeda" ),
        ( "Artillery", "heroes/kongor/artillery" ),
        ( "Blitz", "heroes/kongor/blitz" ),
        ( "Night Hound", "heroes/kongor/hantumon" ),
        ( "Swiftblade", "heroes/kongor/hiro" ),
        ( "Master Of Arms", "heroes/kongor/master_of_arms" ),
        ( "Moira", "heroes/kongor/moira" ),
        ( "Monkey King", "heroes/kongor/monkey_king" ),
        ( "Nitro", "heroes/kongor/nitro" ),
        ( "Nomad", "heroes/kongor/nomad" ),
        ( "Sapphire", "heroes/kongor/sapphire" ),
        ( "Scout", "heroes/kongor/scout" ),
        ( "Silhouette", "heroes/kongor/silhouette" ),
        ( "Sir Benzington", "heroes/kongor/sir_benzington" ),
        ( "Tarot", "heroes/kongor/tarot" ),
        ( "Valkyrie", "heroes/kongor/valkyrie" ),
        ( "Wildsoul", "heroes/kongor/yogi" ),
        ( "Zephyr", "heroes/kongor/zephyr" ),
        ( "Arachna", "heroes/kongor/arachna" ),
        ( "Blood Hunter", "heroes/kongor/hunter" ),
        ( "Bushwack", "heroes/kongor/bushwack" ),
        ( "Chronos", "heroes/kongor/chronos" ),
        ( "Dampeer", "heroes/kongor/dampeer" ),
        ( "Flint Beastwood", "heroes/kongor/flint_beastwood" ),
        ( "Forsaken Archer", "heroes/kongor/forsaken_archer" ),
        ( "Grinex", "heroes/kongor/grinex" ),
        ( "Gunblade", "heroes/kongor/gunblade" ),
        ( "Shadowblade", "heroes/kongor/shadowblade" ),
        ( "Calamity", "heroes/kongor/calamity" ),
        ( "Corrupted Disciple", "heroes/kongor/corrupted_disciple" ),
        ( "Slither", "heroes/kongor/ebulus" ),
        ( "Gemini", "heroes/kongor/gemini" ),
        ( "Klanx", "heroes/kongor/klanx" ),
        ( "Riptide", "heroes/kongor/riptide" ),
        ( "Sand Wraith", "heroes/kongor/sand_wraith" ),
        ( "The Madman", "heroes/kongor/scar" ),
        ( "Soulstealer", "heroes/kongor/soulstealer" ),
        ( "Tremble", "heroes/kongor/tremble" ),
        ( "The Dark Lady", "heroes/kongor/vanya" ),
    ],
    "int": [
        ( "Aluna", "heroes/kongor/aluna" ),
        ( "Blacksmith", "heroes/kongor/dwarf_magi" ),
        ( "Bombardier", "heroes/kongor/bomb" ),
        ( "Ellonia", "heroes/kongor/ellonia" ),
        ( "Engineer", "heroes/kongor/engineer" ),
        ( "Midas", "heroes/kongor/midas" ),
        ( "Pyromancer", "heroes/kongor/pyromancer" ),
        ( "Rhapsody", "heroes/kongor/rhapsody" ),
        ( "Witch Slayer", "heroes/kongor/witch_slayer" ),
        ( "Bubbles", "heroes/kongor/bubbles" ),
        ( "Qi", "heroes/kongor/chi" ),
        ( "The Chipper", "heroes/kongor/chipper" ),
        ( "Empath", "heroes/kongor/empath" ),
        ( "Nymphora", "heroes/kongor/fairy" ),
        ( "Kinesis", "heroes/kongor/kenisis" ),
        ( "Thunderbringer", "heroes/kongor/kunas" ),
        ( "Martyr", "heroes/kongor/martyr" ),
        ( "Monarch", "heroes/kongor/monarch" ),
        ( "Oogie", "heroes/kongor/oogie" ),
        ( "Ophelia", "heroes/kongor/ophelia" ),
        ( "Pearl", "heroes/kongor/pearl" ),
        ( "Pollywog Priest", "heroes/kongor/pollywogpriest" ),
        ( "Skrap", "heroes/kongor/skrap" ),
        ( "Tempest", "heroes/kongor/tempest" ),
        ( "Vindicator", "heroes/kongor/vindicator" ),
        ( "Warchief", "heroes/kongor/warchief" ),
        ( "Defiler", "heroes/kongor/defiler" ),
        ( "Demented Shaman", "heroes/kongor/shaman" ),
        ( "Doctor Repulsor", "heroes/kongor/doctor_repulsor" ),
        ( "Glacius", "heroes/kongor/frosty" ),
        ( "Gravekeeper", "heroes/kongor/taint" ),
        ( "Myrmidon", "heroes/kongor/hydromancer" ),
        ( "Parasite", "heroes/kongor/parasite" ),
        ( "Plague Rider", "heroes/kongor/diseasedrider" ),
        ( "Revenant", "heroes/kongor/revenant" ),
        ( "Soul Reaper", "heroes/kongor/helldemon" ),
        ( "Succubus", "heroes/kongor/succubis" ),
        ( "Wretched Hag", "heroes/kongor/babayaga" ),
        ( "Artesia", "heroes/kongor/artesia" ),
        ( "Circe", "heroes/kongor/circe" ),
        ( "Fayde", "heroes/kongor/fade" ),
        ( "Geomancer", "heroes/kongor/geomancer" ),
        ( "Goldenveil", "heroes/kongor/goldenveil" ),
        ( "Hellbringer", "heroes/kongor/hellbringer" ),
        ( "Parallax", "heroes/kongor/parallax" ),
        ( "Prophet", "heroes/kongor/prophet" ),
        ( "Puppet Master", "heroes/kongor/puppetmaster" ),
        ( "Riftwalker", "heroes/kongor/riftmage" ),
        ( "Voodoo Jester", "heroes/kongor/voodoo" ),
        ( "Torturer", "heroes/kongor/xalynx" ),
    ],
    "str": [
        ( "Armadon", "heroes/kongor/armadon" ),
        ( "Hammerstorm", "heroes/kongor/hammerstorm" ),
        ( "Legionnaire", "heroes/kongor/legionnaire" ),
        ( "Magebane", "heroes/kongor/javaras" ),
        ( "Pandamonium", "heroes/kongor/panda" ),
        ( "Predator", "heroes/kongor/predator" ),
        ( "Prisoner 945", "heroes/kongor/prisoner" ),
        ( "Rally", "heroes/kongor/rally" ),
        ( "Behemoth", "heroes/kongor/behemoth" ),
        ( "Berzerker", "heroes/kongor/berzerker" ),
        ( "Drunken Master", "heroes/kongor/drunkenmaster" ),
        ( "Flux", "heroes/kongor/flux" ),
        ( "The Gladiator", "heroes/kongor/gladiator" ),
        ( "Ichor", "heroes/kongor/ichor" ),
        ( "Jeraziah", "heroes/kongor/jereziah" ),
        ( "Xemplar", "heroes/kongor/mimix" ),
        ( "Bramble", "heroes/kongor/plant" ),
        ( "Rampage", "heroes/kongor/rampage" ),
        ( "Pebbles", "heroes/kongor/rocky" ),
        ( "Salomon", "heroes/kongor/salomon" ),
        ( "Shellshock", "heroes/kongor/shellshock" ),
        ( "Solstice", "heroes/kongor/solstice" ),
        ( "Keeper of the Forest", "heroes/kongor/treant" ),
        ( "Tundra", "heroes/kongor/tundra" ),
        ( "Balphagore", "heroes/kongor/bephelgor" ),
        ( "Magmus", "heroes/kongor/magmar" ),
        ( "Maliken", "heroes/kongor/maliken" ),
        ( "Ravenor", "heroes/kongor/ravenor" ),
        ( "Amun-Ra", "heroes/kongor/ra" ),
        ( "Accursed", "heroes/kongor/accursed" ),
        ( "Adrenaline", "heroes/kongor/adrenaline" ),
        ( "Apex", "heroes/kongor/apex" ),
        ( "Cthulhuphant", "heroes/kongor/cthulhuphant" ),
        ( "Deadlift", "heroes/kongor/deadlift" ),
        ( "Deadwood", "heroes/kongor/deadwood" ),
        ( "Devourer", "heroes/kongor/devourer" ),
        ( "Lord Salforis", "heroes/kongor/dreadknight" ),
        ( "Electrician", "heroes/kongor/electrician" ),
        ( "Draconis", "heroes/kongor/flamedragon" ),
        ( "Gauntlet", "heroes/kongor/gauntlet" ),
        ( "Kane", "heroes/kongor/kane" ),
        ( "King Klout", "heroes/kongor/king_klout" ),
        ( "Kraken", "heroes/kongor/kraken" ),
        ( "Lodestone", "heroes/kongor/lodestone" ),
        ( "Moraxus", "heroes/kongor/moraxus" ),
        ( "Pharaoh", "heroes/kongor/mumra" ),
        ( "Pestilence", "heroes/kongor/pestilence" ),
        ( "War Beast", "heroes/kongor/wolfman" ),
    ],
}

reborn = {
    "agi": [
        ( "Andromeda", "heroes/reborn/andromeda" ),
        ( "Arachna", "heroes/reborn/arachna" ),
        ( "Blood Hunter", "heroes/reborn/blood_hunter" ),
        ( "Chronos", "heroes/reborn/chronos" ),
        ( "Corrupted Disciple", "heroes/reborn/corrupted_disciple" ),
        ( "Dampeer", "heroes/reborn/dampeer" ),
        ( "Emerald Warden", "heroes/reborn/emerald_warden" ),
        ( "Engineer", "heroes/reborn/engineer" ),
        ( "Flint Beastwood", "heroes/reborn/flint_beastwood" ),
        ( "Forsaken Archer", "heroes/reborn/forsaken_archer" ),
        ( "Gemini", "heroes/reborn/gemini" ),
        ( "Gunblade", "heroes/reborn/gunblade" ),
        ( "The Madman", "heroes/reborn/madman" ),
        ( "Master Of Arms", "heroes/reborn/master_of_arms" ),
        ( "Monkey King", "heroes/reborn/monkey_king" ),
        ( "Moon Queen", "heroes/reborn/moon_queen" ),
        ( "Night Hound", "heroes/reborn/night_hound" ),
        ( "Nomad", "heroes/reborn/nomad" ),
        ( "Riptide", "heroes/reborn/riptide" ),
        ( "Sand Wraith", "heroes/reborn/sand_wraith" ),
        ( "Scout", "heroes/reborn/scout" ),
        ( "Silhouette", "heroes/reborn/silhouette" ),
        ( "Sir Benzington", "heroes/reborn/sir_benzington" ),
        ( "Slither", "heroes/reborn/slither" ),
        ( "Soulstealer", "heroes/reborn/soulstealer" ),
        ( "Swiftblade", "heroes/reborn/swiftblade" ),
        ( "Valkyrie", "heroes/reborn/valkyrie" ),
        ( "Zephyr", "heroes/reborn/zephyr" ),
    ],
    "int": [
        ( "Aluna", "heroes/reborn/aluna" ),
        ( "Blacksmith", "heroes/reborn/blacksmith" ),
        ( "Bombardier", "heroes/reborn/bombardier" ),
        ( "Bubbles", "heroes/reborn/bubbles" ),
        ( "The Chipper", "heroes/reborn/chipper" ),
        ( "Defiler", "heroes/reborn/defiler" ),
        ( "Demented Shaman", "heroes/reborn/demented_shaman" ),
        ( "Doctor Repulsor", "heroes/reborn/doctor_repulsor" ),
        ( "Ellonia", "heroes/reborn/ellonia" ),
        ( "Empath", "heroes/reborn/empath" ),
        ( "Fayde", "heroes/reborn/fayde" ),
        ( "Geomancer", "heroes/reborn/geomancer" ),
        ( "Glacius", "heroes/reborn/glacius" ),
        ( "Hellbringer", "heroes/reborn/hellbringer" ),
        ( "Kinesis", "heroes/reborn/kinesis" ),
        ( "Martyr", "heroes/reborn/martyr" ),
        ( "Midas", "heroes/reborn/midas" ),
        ( "Monarch", "heroes/reborn/monarch" ),
        ( "Myrmidon", "heroes/reborn/myrmidon" ),
        ( "Nymphora", "heroes/reborn/nymphora" ),
        ( "Ophelia", "heroes/reborn/ophelia" ),
        ( "Pearl", "heroes/reborn/pearl" ),
        ( "Plague Rider", "heroes/reborn/plague_rider" ),
        ( "Pollywog Priest", "heroes/reborn/pollywog_priest" ),
        ( "Prophet", "heroes/reborn/prophet" ),
        ( "Puppet Master", "heroes/reborn/puppet_master" ),
        ( "Pyromancer", "heroes/reborn/pyromancer" ),
        ( "Revenant", "heroes/reborn/revenant" ),
        ( "Rhapsody", "heroes/reborn/rhapsody" ),
        ( "Riftwalker", "heroes/reborn/riftwalker" ),
        ( "Soul Reaper", "heroes/reborn/soul_reaper" ),
        ( "Tempest", "heroes/reborn/tempest" ),
        ( "Thunderbringer", "heroes/reborn/thunderbringer" ),
        ( "Torturer", "heroes/reborn/torturer" ),
        ( "Vindicator", "heroes/reborn/vindicator" ),
        ( "Voodoo Jester", "heroes/reborn/voodoo_jester" ),
        ( "Witch Slayer", "heroes/reborn/witch_slayer" ),
        ( "Wretched Hag", "heroes/reborn/wretched_hag" ),
    ],
    "str": [
        ( "Accursed", "heroes/reborn/accursed" ),
        ( "Amun-Ra", "heroes/reborn/amun_ra" ),
        ( "Armadon", "heroes/reborn/armadon" ),
        ( "Behemoth", "heroes/reborn/behemoth" ),
        ( "Cthulhuphant", "heroes/reborn/cthulhuphant" ),
        ( "Deadwood", "heroes/reborn/deadwood" ),
        ( "Devourer", "heroes/reborn/devourer" ),
        ( "Drunken Master", "heroes/reborn/drunken_master" ),
        ( "Electrician", "heroes/reborn/electrician" ),
        ( "Flux", "heroes/reborn/flux" ),
        ( "Gauntlet", "heroes/reborn/gauntlet" ),
        ( "The Gladiator", "heroes/reborn/gladiator" ),
        ( "Hammerstorm", "heroes/reborn/hammerstorm" ),
        ( "Jeraziah", "heroes/reborn/jeraziah" ),
        ( "Keeper of the Forest", "heroes/reborn/keeper_of_the_forest" ),
        ( "King Klout", "heroes/reborn/king_klout" ),
        ( "Kraken", "heroes/reborn/kraken" ),
        ( "Legionnaire", "heroes/reborn/legionnaire" ),
        ( "Lodestone", "heroes/reborn/lodestone" ),
        ( "Magebane", "heroes/reborn/magebane" ),
        ( "Magmus", "heroes/reborn/magmus" ),
        ( "Maliken", "heroes/reborn/maliken" ),
        ( "Moraxus", "heroes/reborn/moraxus" ),
        ( "Pandamonium", "heroes/reborn/pandamonium" ),
        ( "Pebbles", "heroes/reborn/pebbles" ),
        ( "Pestilence", "heroes/reborn/pestilence" ),
        ( "Pharaoh", "heroes/reborn/pharaoh" ),
        ( "Predator", "heroes/reborn/predator" ),
        ( "Rampage", "heroes/reborn/rampage" ),
        ( "Ravenor", "heroes/reborn/ravenor" ),
        ( "Solstice", "heroes/reborn/solstice" ),
        ( "Tundra", "heroes/reborn/tundra" ),
        ( "War Beast", "heroes/reborn/war_beast" ),
    ],
}
