kongor = {
    "path": "heroes/kongor",
    "agi": [
        ( "Emerald Warden", "emerald_warden" ),
        ( "Moon Queen", "krixi" ),
        ( "Andromeda", "andromeda" ),
        ( "Artillery", "artillery" ),
        ( "Blitz", "blitz" ),
        ( "Night Hound", "hantumon" ),
        ( "Swiftblade", "hiro" ),
        ( "Master Of Arms", "master_of_arms" ),
        ( "Moira", "moira" ),
        ( "Monkey King", "monkey_king" ),
        ( "Nitro", "nitro" ),
        ( "Nomad", "nomad" ),
        ( "Sapphire", "sapphire" ),
        ( "Scout", "scout" ),
        ( "Silhouette", "silhouette" ),
        ( "Sir Benzington", "sir_benzington" ),
        ( "Tarot", "tarot" ),
        ( "Valkyrie", "valkyrie" ),
        ( "Wildsoul", "yogi" ),
        ( "Zephyr", "zephyr" ),
        ( "Arachna", "arachna" ),
        ( "Blood Hunter", "hunter" ),
        ( "Bushwack", "bushwack" ),
        ( "Chronos", "chronos" ),
        ( "Dampeer", "dampeer" ),
        ( "Flint Beastwood", "flint_beastwood" ),
        ( "Forsaken Archer", "forsaken_archer" ),
        ( "Grinex", "grinex" ),
        ( "Gunblade", "gunblade" ),
        ( "Shadowblade", "shadowblade" ),
        ( "Calamity", "calamity" ),
        ( "Corrupted Disciple", "corrupted_disciple" ),
        ( "Slither", "ebulus" ),
        ( "Gemini", "gemini" ),
        ( "Klanx", "klanx" ),
        ( "Riptide", "riptide" ),
        ( "Sand Wraith", "sand_wraith" ),
        ( "The Madman", "scar" ),
        ( "Soulstealer", "soulstealer" ),
        ( "Tremble", "tremble" ),
        ( "The Dark Lady", "vanya" ),
    ],
    "int": [
        ( "Aluna", "aluna" ),
        ( "Blacksmith", "dwarf_magi" ),
        ( "Bombardier", "bomb" ),
        ( "Ellonia", "ellonia" ),
        ( "Engineer", "engineer" ),
        ( "Midas", "midas" ),
        ( "Pyromancer", "pyromancer" ),
        ( "Rhapsody", "rhapsody" ),
        ( "Witch Slayer", "witch_slayer" ),
        ( "Bubbles", "bubbles" ),
        ( "Qi", "chi" ),
        ( "The Chipper", "chipper" ),
        ( "Empath", "empath" ),
        ( "Nymphora", "fairy" ),
        ( "Kinesis", "kenisis" ),
        ( "Thunderbringer", "kunas" ),
        ( "Martyr", "martyr" ),
        ( "Monarch", "monarch" ),
        ( "Oogie", "oogie" ),
        ( "Ophelia", "ophelia" ),
        ( "Pearl", "pearl" ),
        ( "Pollywog Priest", "pollywogpriest" ),
        ( "Skrap", "skrap" ),
        ( "Tempest", "tempest" ),
        ( "Vindicator", "vindicator" ),
        ( "Warchief", "warchief" ),
        ( "Defiler", "defiler" ),
        ( "Demented Shaman", "shaman" ),
        ( "Doctor Repulsor", "doctor_repulsor" ),
        ( "Glacius", "frosty" ),
        ( "Gravekeeper", "taint" ),
        ( "Myrmidon", "hydromancer" ),
        ( "Parasite", "parasite" ),
        ( "Plague Rider", "diseasedrider" ),
        ( "Revenant", "revenant" ),
        ( "Soul Reaper", "helldemon" ),
        ( "Succubus", "succubis" ),
        ( "Wretched Hag", "babayaga" ),
        ( "Artesia", "artesia" ),
        ( "Circe", "circe" ),
        ( "Fayde", "fade" ),
        ( "Geomancer", "geomancer" ),
        ( "Goldenveil", "goldenveil" ),
        ( "Hellbringer", "hellbringer" ),
        ( "Parallax", "parallax" ),
        ( "Prophet", "prophet" ),
        ( "Puppet Master", "puppetmaster" ),
        ( "Riftwalker", "riftmage" ),
        ( "Voodoo Jester", "voodoo" ),
        ( "Torturer", "xalynx" ),
    ],
    "str": [
        ( "Armadon", "armadon" ),
        ( "Hammerstorm", "hammerstorm" ),
        ( "Legionnaire", "legionnaire" ),
        ( "Magebane", "javaras" ),
        ( "Pandamonium", "panda" ),
        ( "Predator", "predator" ),
        ( "Prisoner 945", "prisoner" ),
        ( "Rally", "rally" ),
        ( "Behemoth", "behemoth" ),
        ( "Berzerker", "berzerker" ),
        ( "Drunken Master", "drunkenmaster" ),
        ( "Flux", "flux" ),
        ( "The Gladiator", "gladiator" ),
        ( "Ichor", "ichor" ),
        ( "Jeraziah", "jereziah" ),
        ( "Xemplar", "mimix" ),
        ( "Bramble", "plant" ),
        ( "Rampage", "rampage" ),
        ( "Pebbles", "rocky" ),
        ( "Salomon", "salomon" ),
        ( "Shellshock", "shellshock" ),
        ( "Solstice", "solstice" ),
        ( "Keeper of the Forest", "treant" ),
        ( "Tundra", "tundra" ),
        ( "Balphagore", "bephelgor" ),
        ( "Magmus", "magmar" ),
        ( "Maliken", "maliken" ),
        ( "Ravenor", "ravenor" ),
        ( "Amun-Ra", "ra" ),
        ( "Accursed", "accursed" ),
        ( "Adrenaline", "adrenaline" ),
        ( "Apex", "apex" ),
        ( "Cthulhuphant", "cthulhuphant" ),
        ( "Deadlift", "deadlift" ),
        ( "Deadwood", "deadwood" ),
        ( "Devourer", "devourer" ),
        ( "Lord Salforis", "dreadknight" ),
        ( "Electrician", "electrician" ),
        ( "Draconis", "flamedragon" ),
        ( "Gauntlet", "gauntlet" ),
        ( "Kane", "kane" ),
        ( "King Klout", "king_klout" ),
        ( "Kraken", "kraken" ),
        ( "Lodestone", "lodestone" ),
        ( "Moraxus", "moraxus" ),
        ( "Pharaoh", "mumra" ),
        ( "Pestilence", "pestilence" ),
        ( "War Beast", "wolfman" ),
    ],
}

reborn = {
    "path": "heroes/reborn",
    "agi": [
        ( "Andromeda", "andromeda" ),
        ( "Arachna", "arachna" ),
        ( "Blood Hunter", "blood_hunter" ),
        ( "Chronos", "chronos" ),
        ( "Corrupted Disciple", "corrupted_disciple" ),
        ( "Dampeer", "dampeer" ),
        ( "Emerald Warden", "emerald_warden" ),
        ( "Engineer", "engineer" ),
        ( "Flint Beastwood", "flint_beastwood" ),
        ( "Forsaken Archer", "forsaken_archer" ),
        ( "Gemini", "gemini" ),
        ( "Gunblade", "gunblade" ),
        ( "The Madman", "madman" ),
        ( "Master Of Arms", "master_of_arms" ),
        ( "Monkey King", "monkey_king" ),
        ( "Moon Queen", "moon_queen" ),
        ( "Night Hound", "night_hound" ),
        ( "Nomad", "nomad" ),
        ( "Riptide", "riptide" ),
        ( "Sand Wraith", "sand_wraith" ),
        ( "Scout", "scout" ),
        ( "Shadowblade", "shadowblade" ),
        ( "Silhouette", "silhouette" ),
        ( "Sir Benzington", "sir_benzington" ),
        ( "Slither", "slither" ),
        ( "Soulstealer", "soulstealer" ),
        ( "Swiftblade", "swiftblade" ),
        ( "Valkyrie", "valkyrie" ),
        ( "Zephyr", "zephyr" ),
    ],
    "int": [
        ( "Aluna", "aluna" ),
        ( "Blacksmith", "blacksmith" ),
        ( "Bombardier", "bombardier" ),
        ( "Bubbles", "bubbles" ),
        ( "The Chipper", "chipper" ),
        ( "Defiler", "defiler" ),
        ( "Demented Shaman", "demented_shaman" ),
        ( "Doctor Repulsor", "doctor_repulsor" ),
        ( "Ellonia", "ellonia" ),
        ( "Empath", "empath" ),
        ( "Fayde", "fayde" ),
        ( "Geomancer", "geomancer" ),
        ( "Glacius", "glacius" ),
        ( "Hellbringer", "hellbringer" ),
        ( "Kinesis", "kinesis" ),
        ( "Martyr", "martyr" ),
        ( "Midas", "midas" ),
        ( "Monarch", "monarch" ),
        ( "Myrmidon", "myrmidon" ),
        ( "Nymphora", "nymphora" ),
        ( "Ophelia", "ophelia" ),
        ( "Pearl", "pearl" ),
        ( "Plague Rider", "plague_rider" ),
        ( "Pollywog Priest", "pollywog_priest" ),
        ( "Prophet", "prophet" ),
        ( "Puppet Master", "puppet_master" ),
        ( "Pyromancer", "pyromancer" ),
        ( "Revenant", "revenant" ),
        ( "Rhapsody", "rhapsody" ),
        ( "Riftwalker", "riftwalker" ),
        ( "Soul Reaper", "soul_reaper" ),
        ( "Tempest", "tempest" ),
        ( "Thunderbringer", "thunderbringer" ),
        ( "Torturer", "torturer" ),
        ( "Vindicator", "vindicator" ),
        ( "Voodoo Jester", "voodoo_jester" ),
        ( "Witch Slayer", "witch_slayer" ),
        ( "Wretched Hag", "wretched_hag" ),
    ],
    "str": [
        ( "Accursed", "accursed" ),
        ( "Amun-Ra", "amun_ra" ),
        ( "Armadon", "armadon" ),
        ( "Behemoth", "behemoth" ),
        ( "Cthulhuphant", "cthulhuphant" ),
        ( "Deadwood", "deadwood" ),
        ( "Devourer", "devourer" ),
        ( "Drunken Master", "drunken_master" ),
        ( "Electrician", "electrician" ),
        ( "Flux", "flux" ),
        ( "Gauntlet", "gauntlet" ),
        ( "The Gladiator", "gladiator" ),
        ( "Hammerstorm", "hammerstorm" ),
        ( "Jeraziah", "jeraziah" ),
        ( "Keeper of the Forest", "keeper_of_the_forest" ),
        ( "King Klout", "king_klout" ),
        ( "Kraken", "kraken" ),
        ( "Legionnaire", "legionnaire" ),
        ( "Lodestone", "lodestone" ),
        ( "Magebane", "magebane" ),
        ( "Magmus", "magmus" ),
        ( "Maliken", "maliken" ),
        ( "Moraxus", "moraxus" ),
        ( "Pandamonium", "pandamonium" ),
        ( "Pebbles", "pebbles" ),
        ( "Pestilence", "pestilence" ),
        ( "Pharaoh", "pharaoh" ),
        ( "Predator", "predator" ),
        ( "Rampage", "rampage" ),
        ( "Ravenor", "ravenor" ),
        ( "Solstice", "solstice" ),
        ( "Tundra", "tundra" ),
        ( "War Beast", "war_beast" ),
    ],
}
